# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: dotnet tool restore
  displayName: 'Restore Tools'

- script: dotnet gitversion /output buildserver /nofetch
  displayName: 'GitVersion'

- script: dotnet cake --target=DockerBuild
  displayName: 'Docker Build'

- script: dotnet cake --target=DockerPush
  displayName: 'Docker Push'
  env:
    DOCKER_REPOSITORY_PASSWORD: $(DOCKER_REPOSITORY_PASSWORD)

- script: dotnet cake --target=NuGetPack
  displayName: 'NuGet Pack'

- script: dotnet cake --target=NuGetPush
  displayName: 'NuGet Push'
  env:
    NUGET_API_KEY: $(NUGET_API_KEY)
